services:
  node_1:
    image: message_mode
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - HOST=node_1
      - PORT=5000
    networks:
      messages_app_network:
        ipv4_address: 10.5.0.5
  node_2:
    image: message_mode
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - HOST=node_2
      - PORT=5000
    networks:
      messages_app_network:
        ipv4_address: 10.5.0.6

networks:
  messages_app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1