services:
  node_1:
    working_dir: /app
    environment:
      - HOST=node_1
      - NODE_N=1
      - PORT=5000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      messages_app_network:
        ipv4_address: 10.5.0.5

  node_2:
    working_dir: /app
    environment:
      - HOST=node_2
      - NODE_N=2
      - PORT=5000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      messages_app_network:
        ipv4_address: 10.5.0.6

  node_3:
    working_dir: /app
    environment:
      - HOST=node_3
      - NODE_N=3
      - PORT=5000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      messages_app_network:
        ipv4_address: 10.5.0.7

networks:
  messages_app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1