version: '3.3'
services:
  node_1:
    working_dir: /app
    environment:
      - HOST=node_1
      - NODE_N=1
      - PORT=5000
      - DB_HOST=10.5.1.5
      - BD_USER=root
      - DB_PASSWORD=password123
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_1
    networks:
      messages_app_network:
        ipv4_address: 10.5.0.5

  db_1:
    environment:
      MARIADB_ROOT_PASSWORD: 'password123'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
      MARIADB_DATABASE: 'db_tickets'
    image: mariadb
    volumes:
      - .db1/:/var/lib/mysql
    networks:
      messages_app_network:
        ipv4_address: 10.5.1.5

  node_2:
    working_dir: /app
    environment:
      - HOST=node_2
      - NODE_N=2
      - PORT=5000
      - DB_HOST=10.5.1.6
      - BD_USER=root
      - DB_PASSWORD=password123
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_2
    networks:
      messages_app_network:
        ipv4_address: 10.5.0.6

  db_2:
    environment:
      MARIADB_ROOT_PASSWORD: 'password123'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
      MARIADB_DATABASE: 'db_tickets'
    image: mariadb
    volumes:
      - .db2/:/var/lib/mysql
    networks:
      messages_app_network:
        ipv4_address: 10.5.1.6

  node_3:
    working_dir: /app
    environment:
      - HOST=node_3
      - NODE_N=3
      - PORT=5000
      - DB_HOST=10.5.1.7
      - BD_USER=root
      - DB_PASSWORD=password123
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_3
    networks:
      messages_app_network:
        ipv4_address: 10.5.0.7

  db_3:
    environment:
      MARIADB_ROOT_PASSWORD: 'password123'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
      MARIADB_DATABASE: 'db_tickets'
    image: mariadb
    volumes:
      - .db3/:/var/lib/mysql
    networks:
      messages_app_network:
        ipv4_address: 10.5.1.7

networks:
  messages_app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1